# Generated by Django 3.1.2 on 2020-11-05 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='personal_Info',
            fields=[
                ('pi_pk', models.AutoField(primary_key=True, serialize=False)),
                ('sur_name', models.CharField(max_length=75)),
                ('first_name', models.CharField(max_length=75)),
                ('middle_name', models.CharField(blank=True, max_length=75, null=True)),
                ('name_ext', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateField()),
                ('pace_of_birth', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=10)),
                ('civil_status', models.CharField(max_length=15)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('blood_type', models.CharField(max_length=5)),
                ('gsis_id_no', models.IntegerField()),
                ('pagibig_id_no', models.IntegerField()),
                ('philhealth_no', models.IntegerField()),
                ('sss_no', models.IntegerField()),
                ('tin_no', models.IntegerField()),
                ('agency_employee_no', models.IntegerField()),
                ('citizenship', models.IntegerField(choices=[(0, 'Filipino'), (1, 'Dual Citizenship by birth'), (2, 'Dual Citizenship by naturalization')])),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('res_lot_no', models.CharField(max_length=20)),
                ('res_street', models.CharField(max_length=75)),
                ('res_subd', models.CharField(max_length=50)),
                ('res_brgy', models.CharField(max_length=50)),
                ('res_city', models.CharField(max_length=50)),
                ('res_province', models.CharField(max_length=50)),
                ('res_zipcode', models.IntegerField()),
                ('per_lot_no', models.CharField(max_length=20)),
                ('per_street', models.CharField(max_length=75)),
                ('per_subd', models.CharField(max_length=50)),
                ('per_brgy', models.CharField(max_length=50)),
                ('per_city', models.CharField(max_length=50)),
                ('per_province', models.CharField(max_length=50)),
                ('per_zipcode', models.IntegerField()),
                ('telephone', models.IntegerField()),
                ('mobile_no', models.IntegerField()),
                ('email_address', models.CharField(max_length=75)),
                ('photo', models.CharField(max_length=100)),
                ('date_accomplished', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='work_Experience',
            fields=[
                ('we_pk', models.AutoField(primary_key=True, serialize=False)),
                ('inclusive_dates_from', models.DateField(blank=True, null=True)),
                ('inclusive_dates_to', models.DateField(blank=True, null=True)),
                ('position_title', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.CharField(blank=True, max_length=75, null=True)),
                ('monthly_salary', models.IntegerField(blank=True, null=True)),
                ('pay_grade', models.IntegerField(blank=True, null=True)),
                ('status_of_appointment', models.CharField(blank=True, max_length=50, null=True)),
                ('govt_service', models.BooleanField(blank=True, default=False, null=True)),
                ('we_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apply.personal_info')),
            ],
        ),
        migrations.CreateModel(
            name='voluntary_Work',
            fields=[
                ('vw_pk', models.AutoField(primary_key=True, serialize=False)),
                ('name_add_org', models.CharField(blank=True, max_length=300, null=True)),
                ('inclusive_date_from', models.DateField(blank=True, null=True)),
                ('inclusive_date_to', models.DateField(blank=True, null=True)),
                ('number_of_hours', models.IntegerField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('vw_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apply.personal_info')),
            ],
        ),
        migrations.CreateModel(
            name='training_Attended',
            fields=[
                ('ta_pk', models.AutoField(primary_key=True, serialize=False)),
                ('title_of_training', models.CharField(blank=True, max_length=100, null=True)),
                ('inclusive_date_from', models.DateField(blank=True, null=True)),
                ('inclusive_date_to', models.DateField(blank=True, null=True)),
                ('number_of_hours', models.IntegerField(blank=True, null=True)),
                ('type_of_LD', models.CharField(blank=True, max_length=75, null=True)),
                ('conducted_by', models.CharField(blank=True, max_length=150, null=True)),
                ('ta_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apply.personal_info')),
            ],
        ),
        migrations.CreateModel(
            name='References',
            fields=[
                ('ref_pk', models.AutoField(primary_key=True, serialize=False)),
                ('ref_name', models.CharField(max_length=150)),
                ('ref_address', models.CharField(max_length=200)),
                ('ref_telephone', models.IntegerField()),
                ('ref_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apply.personal_info')),
            ],
        ),
        migrations.CreateModel(
            name='other_Info',
            fields=[
                ('oi_pk', models.AutoField(primary_key=True, serialize=False)),
                ('special_skills', models.CharField(blank=True, max_length=75, null=True)),
                ('non_acad_recognition', models.CharField(blank=True, max_length=100, null=True)),
                ('membership', models.CharField(blank=True, max_length=100, null=True)),
                ('oi_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apply.personal_info')),
            ],
        ),
        migrations.CreateModel(
            name='issued_Govt',
            fields=[
                ('ig_pk', models.AutoField(primary_key=True, serialize=False)),
                ('id_name', models.CharField(max_length=100)),
                ('id_no', models.IntegerField()),
                ('date_place_of_issuance', models.CharField(max_length=100)),
                ('ig_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apply.personal_info')),
            ],
        ),
        migrations.CreateModel(
            name='family_Background',
            fields=[
                ('fb_pk', models.AutoField(primary_key=True, serialize=False)),
                ('spouse_sur_name', models.CharField(blank=True, max_length=75, null=True)),
                ('spouse_first_name', models.CharField(blank=True, max_length=75, null=True)),
                ('spouse_middle_name', models.CharField(blank=True, max_length=75, null=True)),
                ('spouse_name_ext', models.CharField(blank=True, max_length=20, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('business_name', models.CharField(blank=True, max_length=150, null=True)),
                ('business_address', models.CharField(blank=True, max_length=200, null=True)),
                ('spouse_telephone', models.IntegerField(blank=True, null=True)),
                ('father_sur_name', models.CharField(max_length=75)),
                ('father_first_name', models.CharField(max_length=75)),
                ('father_middle_name', models.CharField(blank=True, max_length=75, null=True)),
                ('father_name_ext', models.CharField(blank=True, max_length=20, null=True)),
                ('mother_sur_name', models.CharField(max_length=75)),
                ('mother_first_name', models.CharField(max_length=75)),
                ('mother_middle_name', models.CharField(blank=True, max_length=75, null=True)),
                ('fb_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apply.personal_info')),
            ],
        ),
        migrations.CreateModel(
            name='educational_Background',
            fields=[
                ('eb_pk', models.AutoField(primary_key=True, serialize=False)),
                ('educ_level', models.CharField(blank=True, choices=[(0, 'Elementary'), (1, 'Secondary'), (2, 'Vocational/Trade Course'), (3, 'College'), (4, 'Graduate Studies')], max_length=40, null=True)),
                ('name_of_school', models.CharField(blank=True, max_length=150, null=True)),
                ('degree', models.CharField(blank=True, max_length=150, null=True)),
                ('period_from', models.DateField(blank=True, null=True)),
                ('period_to', models.DateField(blank=True, null=True)),
                ('highest_level_earned', models.CharField(blank=True, max_length=100, null=True)),
                ('year_grad', models.IntegerField(blank=True, null=True)),
                ('honors', models.CharField(blank=True, max_length=50, null=True)),
                ('eb_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apply.personal_info')),
            ],
        ),
        migrations.CreateModel(
            name='cs_Eligibility',
            fields=[
                ('cse_pk', models.AutoField(primary_key=True, serialize=False)),
                ('eligibility', models.CharField(blank=True, max_length=40, null=True)),
                ('rating', models.CharField(blank=True, max_length=10, null=True)),
                ('date_of_exam', models.DateField(blank=True, null=True)),
                ('place_of_exam', models.CharField(blank=True, max_length=200, null=True)),
                ('license_number', models.IntegerField(blank=True, null=True)),
                ('license_date_of_validity', models.DateField(blank=True, null=True)),
                ('cse_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apply.personal_info')),
            ],
        ),
        migrations.CreateModel(
            name='children_Names',
            fields=[
                ('cn_pk', models.AutoField(primary_key=True, serialize=False)),
                ('child_full_name', models.CharField(blank=True, max_length=150, null=True)),
                ('child_date_of_birth', models.DateField(blank=True, null=True)),
                ('cn_fk', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='apply.personal_info')),
            ],
        ),
    ]
